#########################################################################################
# Name                  steiner:terror
# Description           Rewrite of terror.pl for (He)XChat.
# Credit				Original author is unknown. Modified by fire-eyes, zebra and thinkpol
# Version               1.1 (2015-01-10)
# Contact               ScottSteiner@irc.rizon.net
# Website               https://github.com/ScottSteiner/xchat-scripts
# Copyright             2013, ScottSteiner <nothingfinerthanscottsteiner@gmail.com>
# License               GPL version 3 or any later version; http://www.gnu.org/copyleft/gpl.html
#########################################################################################

import xchat, random, re

__module_name__ = 'steiner:terror'
__module_version__ = '1.0'
__module_description__ = 'Terror alias, rewritten by Scott Steiner'	
firstrun = True

def multiple_replace(string, rep_dict):
    pattern = re.compile('|'.join([re.escape(k) for k in rep_dict.keys()]), re.M)
    return pattern.sub(lambda x: rep_dict[x.group(0)], string)
	
def sent_struct(target):
	if True:
		# PEOPLE
		people = [
			"Albert Einstein",
			"aliens",
			"Alyson",
			"Bantown",
			"Bletchley Park",
			"Bohemian Grove",
			"capitalist oppressors",
			"capitalist pigs",
			"Charles Manson",
			"Chief Deputy Gilberto San Miguel Jr.",
			"christians",
			"chupicabra",
			"Council on Foreign Relations",
			"DALnet irc operators",
			"David Icke",
			"deer hunter",
			"Deutchland national nazi party",
			"Elian Gonzalez",
			"ESR",
			"Europol",
			"FBI hostage rescue team",
			"fraternal socialist allies",
			"GNAA",
			"hostages",
			"illuminati",
			"Interpol",
			"J. Robert Oppenheimer",
			"Jesus Christ",
			"KKK",
			"Ku Klux Klan",
			"L.A. times editor",
			"Lee Harvey Oswald",
			"McDonalds - over 1 billion served",
			"McDonalds drive through attendant",
			"McDonalds waste management",
			"MPAA",
			"Mt Ranier Reserve Parking Attendant",
			"Mudge",
			"N.Y. times editor",
			"Navair",
			"Nazi party",
			"nazis",
			"nightstalkers",
			"Nikolai Tesla",
			"Organization of American States",
			"Oscar Wilde",
			"peacekeeper",
			"president of the united states",
			"reptillians",
			"RIAA",
			"Richard Marcinko",
			"subversives",
			"texas rangers",
			"the crusaders",
			"the girls of islamabad",
			"the jews",
			"the jews and the crusaders",
			"Trilateral Commission",
			"unbelievers",
			"undercover",
			"US citizen",
			"Waihopai",
			"William Cooper",
			"William Marchand",
			"zionist"
		]
		people_entertainers = [
			"Ann Coulter",
			"Art Bell",
			"Bill O'Reilly",
			"George Clinton",
			"George Noory",
			"George Takei",
			"Howard Stern",
			"Kareem Abdul Jabar",
			"Kayne West",
			"Martha Stewart",
			"Noam Chomsky",
			"O.J. Simpson",
			"Rush Limbaugh",
			"Sean Hannity",
			"Wilt Chamberlain",
			"Wu-Tang Clan"
		]
		people_fiction = [
			"Captain Jean-Luc Picard",
			"Captain James T. Kirk",
			"Captain Benjamin Sisko",
			"Captain Kathryn Janeway",
			"Captain Jonathan Arthar",
			"Spock",
			"Lieutenant Worf",
			"Lieutenant Data",
			"Chief Miles O'Brien",
			"Lord Vader",
			"Emperor Palpatine",
			"Luke Skywalker",
			"Leia Organa",
			"Obi-Wan Kenobi",
			"C-3PO",
			"R2-D2",
			"Shepard",
			"Hawk",
			"Grey Warden"
		]
		people_islam = [
			"Akbar",
			"Al Jazeera",
			"Allah",
			"Allah be with you",
			"Allah is great",
			"and with you be Allah",
			"in the name of Allah, the merciful, the compassionate",
			"Mujahideen",
			"Muslim shiite",
			"praise Allah",]
		people_military = [
			"3rd Marine Air wing miramar",
			"5th special forces group",
			"11th shock army",
			"Captain Humberto Versace",
			"Chinese peoples' liberation air force",
			"Chinese peoples' liberation army",
			"Chinese peoples' liberation navy",
			"General Richard Meyers",
			"gunnery sergeant Carlos Hathcock",
			"KGB",
			"Lieutenant Colonel James N. Rowe",
			"LT Colonel James N. Rowe",
			"LT Colonel Oliver North",
			"Major Edward Dames",
			"NSA",
			"Sayeret Matkal",
			"Sayeret Tzanhanim",
			"seal team five",
			"special forces detachment-a",
			"Templar Knights",
			"the delta force",
			"United States coast guard",
			"United States Marine Corps",
			"United States Marine Corps Force Recon",
			"VietCong"
		]
		people_politicians_US_other = [
			"Alan Greenspan",
			"Ben Bernanke",
			"Cindy Shehan",
			"Colin Powell",
			"Condoleezza Rice",
			"Dick Cheney",
			"Edward Kennedy",
			"Harry Whittington",
			"Janet Reno",
			"Karl Rove",
			"Newt Gingrich",
			"Robert Kennedy",
			"Ross Perot",
			"Scooter Libby",
			"Senator Joseph McCarthy",
			"Ted Kennedy",]
		people_politicians_US_supremecourt = [
			"John Roberts", 		# Current Justices
			"Antonin Scalia",
			"Anthony Kennedy",
			"Clarence Thomas",
			"Ruth Bader Ginsburg",
			"Stephen Breyer",
			"Samuel Alito",
			"Sonia Sotomayor",
			"Elena Kagan",
			"David Souter",			# Retired and dead Justices
			"John Paul Stevens",
			"Sandra Day O'Connor",
			"Ted Stevens",
			"William Rehnquist"	]
		people_politicians_US_presidents = [
			#Presidents from 1900-Current
			"Theodore Roosevelt",
			"William Howard Taft",
			"Woodrow Wilson",
			"Warren Harding",
			"Calvin Coolidge",
			"Herbert Hoover",
			"Franklin Roosevelt",
			"Harry Truman",
			"Dwight Eisenhower",
			"John F. Kennedy",
			"Lyndon Johnson",
			"Richard Nixon",
			"Gerald Ford",
			"James Carter",
			"Ronald Reagan",
			"George H. W. Bush",
			"William Clinton",
			"George W. Bush",
			"Barack Obama"
		]
		people_politicians_US_senators = [
			"Richard Shelby",		# Republican - Alabama
			"Jeff Sessions",		# Republican - Alabama
			"Lisa Murkowski",		# Republican - Alaska
			"Mark Begich",			# Democratic - Alaska
			"John McCain",			# Republican - Arizona
			"Jeff Flake",			# Republican - Arizona
			"Mark Pryor",			# Democratic - Arkansas
			"John Boozman",			# Republican - Arkansas
			"Dianne Feinstein",		# Democratic - California
			"Barbara Boxer",		# Democratic - California
			"Mark Udall",			# Democratic - Colorado
			"Michael Bennet",		# Democratic - Colorado
			"Richard Blumenthal",	# Democratic - Connecticut
			"Chris Murphy",			# Democratic - Connecticut
			"Tom Carper",			# Democratic - Delaware
			"Chris Coons",			# Democratic - Delaware
			"Bill Nelson",			# Democratic - Florida
			"Marco Rubio",			# Republican - Florida
			"Saxby Chambliss",		# Republican - Georgia
			"Johnny Isakson",		# Republican - Georgia
			"Brian Schatz",			# Democratic - Hawaii
			"Mazie Hirono",			# Democratic - Hawaii
			"Mike Crapo",			# Republican - Idaho
			"Jim Risch",			# Republican - Idaho
			"Dick Durbin",			# Democratic - Illinois
			"Mark Kirk",			# Republican - Illinois
			"Dan Coats",			# Republican - Indiana
			"Joe Donnelly",			# Democratic - Indiana
			"Chuck Grassley",		# Republican - Iowa
			"Tom Harkin",			# Democratic - Iowa
			"Pat Roberts",			# Republican - Kansas
			"Jerry Moran",			# Republican - Kansas
			"Mitch McConnell",		# Republican - Kentucky
			"Rand Paul",			# Republican - Kentucky
			"Mary Landrieu",		# Democratic - Louisiana
			"David Vitter",			# Republican - Louisiana
			"Susan Collins",		# Republican - Maine
			"Angus King",			# Independent - Maine
			"Barbara Mikulski",		# Democratic - Maryland
			"Ben Cardin",			# Democratic - Maryland
			"Elizabeth Warren",		# Democratic - Massachusetts
			"Mo Cowan",				# Democratic - Massachusetts
			"Carl Levin",			# Democratic - Michigan
			"Debbie Stabenow",		# Democratic - Michigan
			"Amy Klobuchar",		# Democratic - Minnesota
			"Al Franken",			# Democratic - Minnesota
			"Thad Cochran",			# Republican - Mississippi
			"Roger Wicker",			# Republican - Mississippi
			"Claire McCaskill",		# Democratic - Missouri
			"Roy Blunt",			# Republican - Missouri
			"Max Baucus",			# Democratic - Montana
			"Jon Tester",			# Democratic - Montana
			"Mike Johanns",			# Republican - Nebraska
			"Deb Fischer",			# Republican - Nebraska
			"Harry Reid",			# Democratic - Nevada
			"Dean Heller",			# Republican - Nevada
			"Jeanne Shaheen",		# Democratic - New Hampshire
			"Kelly Ayotte",			# Republican - New Hampshire
			"Frank Lautenberg",		# Democratic - New Jersey
			"Bob Menendez",			# Democratic - New Jersey
			"Tom Udall",			# Democratic - New Mexico
			"Martin Heinrich",		# Democratic - New Mexico
			"Chuck Schumer",		# Democratic - New York
			"Kirsten Gillibrand",	# Democratic - New York
			"Richard Burr",			# Republican - North Carolina
			"Kay Hagan",			# Democratic - North Carolina
			"John Hoeven",			# Republican - North Dakota
			"Heidi Heitkamp",		# Democratic - North Dakota
			"Sherrod Brown",		# Democratic - Ohio
			"Rob Portman",			# Republican - Ohio
			"Jim Inhofe",			# Republican - Oklahoma
			"Tom Coburn",			# Republican - Oklahoma
			"Ron Wyden",			# Democratic - Oregon
			"Jeff Merkley",			# Democratic - Oregon
			"Bob Casey, Jr.",		# Democratic - Pennsylvania
			"Pat Toomey",			# Republican - Pennsylvania
			"Jack Reed",			# Democratic - Rhode Island
			"Sheldon Whitehouse",	# Democratic - Rhode Island
			"Lindsey Graham",		# Republican - South Carolina
			"Tim Scott",			# Republican - South Carolina
			"Tim Johnson",			# Democratic - South Dakota
			"John Thune",			# Republican - South Dakota
			"Lamar Alexander",		# Republican - Tennessee
			"Bob Corker",			# Republican - Tennessee
			"John Cornyn",			# Republican - Texas
			"Ted Cruz",				# Republican - Texas
			"Orrin Hatch",			# Republican - Utah
			"Mike Lee",				# Republican - Utah
			"Patrick Leahy",		# Democratic - Vermont
			"Bernie Sanders",		# Independent - Vermont
			"Mark Warner",			# Democratic - Virginia
			"Tim Kaine",			# Democratic - Virginia
			"Patty Murray",			# Democratic - Washington
			"Maria Cantwell",		# Democratic - Washington
			"Jay Rockefeller",		# Democratic - West Virginia
			"Joe Manchin",			# Democratic - West Virginia
			"Ron Johnson",			# Republican - Wisconsin
			"Tammy Baldwin",		# Democratic - Wisconsin
			"Mike Enzi",			# Republican - Wyoming
			"John Barrasso"			# Republican - Wyoming
			]
		people_politicians_World = [
			"Adolf Hitler",
			"Airel Sharon",
			"Duke Leto Atreides",
			"Ehud Olmert",
			"Fidel Castro",
			"Hans Blix",
			"Hitler",
			"Hugo Chavez",
			"Karl Marx",
			"Kim Jong-il",
			"Leon Trotsky",
			"Mahmood Anadinijad",
			"Pope Benedict XVI",
			"Pope John Paul II",
			"Princess Diana",
			"Queen Beatrix",
			"saudi royal family",
			"Vladimir Vladimirovich Putin",
			"Willem van Oranje",
			"Yasser Arafat"
		]
		people_technology = [
			"Bill Gates",
			"Ian Murdock",
			"Richard Stallman",
			"RMS",
			"Steve Case",
			"Theo de Raadt",
			"William Gates",
			"Mark Zuckerberg",
			"Joshua Topolsky",
			"Leo Laporte",
			"Larry Ellison",
			"Jeff Bezos",
			"Larry Page",
			"Sergey Brin",
			"Eric Schmidt",
			"Paul Allen",
			"Steve Jobs",
			"Steve Wozniak"
		]
		people_terrorists = [
			"Abd Al-Raheem",
			"Abdelkarim Hussein Mohamed Al-Nasser",
			"Abdullah Ahmed Abdullah",
			"Abdul Rahman Yasin",
			"Ahmad Ibrahim Al-Mughassil",
			"Ahmed Khalfan Ghailani",
			"Ahmed Mohammed Hamad Ali",
			"Ali Atwa",
			"Ali Saed Bin Ali El-Hoorie",
			"Al Neda",
			"Al Qaeda",
			"Anas Al-Liby",
			"Ayman Al-Zawahiri",
			"Barack Hussein Obama",
			"Black Panthers",
			"Fahid Mohammed Ally Msalam",
			"Fazul Abdullah Mohammed",
			"Hamas",
			"Hasan Izz-Al-Din",
			"Hassan Nasrallah",
			"Ibrahim Salih Mohammed Al-Yacoub",
			"Imad Fayez Mugniyah",
			"Malcolm X",
			"Martin Luther King Jr.",
			"Muhammad Atef",
			"Muhsin Musa Matwalli Atwah",
			"Mustafa Mohamed Fadhil",
			"Osama",
			"Osama Bin Laden",
			"Saif Al-Adel",
			"Sheikh Ahmed Salim Swedan",
			"Sheikh Muqtada Al-Sadr",
			"Trench Coat Mafia"
		]
		people_titles = [
			"commandant of the marine corps",
			"commander in chief strategic air command",
			"executive officer",
			"first lady",
			"green beret",
			"installation commander",
			"secretary of state",
			"secretary of the army",
			"secretary of the navy",
			"secretary of the treasury",
			"senate minority leader",
			"speaker of the house"
		]
		# LOCATIONS
		locations = [
			"1/6th Field Artillery",
			"16 Federal Plaza",
			"36 Chambers",
			"64 Vauxhall Cross",
			"187th Infantry Regiment Headquarters",
			"Air Combat Command (ACC)",
			"Air force agency for modeling and simulation",
			"Air force audit agency",
			"Air force communications",
			"Air force materiel command",
			"Air force medical operations",
			"Air force office of scientific research",
			"Air force office of special investigations",
			"Air Force One",
			"air force one",
			"Air force personnel center",
			"Air force research laboratory",
			"Air force reserve command",
			"Air force reserve officer training corps (AFROTC)",
			"Air force space command",
			"Air Force Space Command (AFSPC)",
			"Air force special operations command",
			"Air force technical applications center",
			"Air Force Two",
			"Air intelligence agency",
			"Air mobility command",
			"Air national guard",
			"Al-Tikrit",
			"Alfred P. Murrah Federal Building",
			"Ames laboratory",
			"Ames research center",
			"Anniston Army Depot",
			"Area 51",
			"Argonne national laboratory",
			"Armed forces radiobiology research institute",
			"Army materiel command",
			"Army medical department",
			"Army research laboratory",
			"Artificial Island",
			"Aryan nation",
			"atomic waste facility",
			"Bermuda Triangle",
			"Bettis atomic power laboratory",
			"Boonsboro",
			"Brandywine",
			"Brookhaven national laboratory",
			"Bunker",
			"Bunker complex",
			"Bureau of arms control",
			"Bureau of consular affairs",
			"Bureau of diplomatic security",
			"Burger King - Have it your way",
			"Bush international airport",
			"Cairo",
			"California",
			"Camp David",
			"Camp McCall",
			"Camp X-ray",
			"Canadian Embassy",
			"Cape Canaveral",
			"Carneys Point in New Jersey",
			"cave complex",
			"Center for biologics evaluation and research",
			"Centers for disease control and prevention",
			"central security service",
			"Cheyenne mountain",
			"Cheyenne Mountain",
			"Chief of naval operations",
			"Cinc Mobile Alternate Headquarters",
			"Civil air patrol",
			"CNN Center, Atlanta",
			"Columbine High School",
			"combat information center",
			"Compton",
			"Condoleeza Rice's underground facility",
			"Constitution Ave",
			"Coral Castle",
			"DARPA",
			"Davidsonville",
			"Defense administrative support center",
			"Defense advanced research projects agency",
			"Defense information systems agency",
			"Defense intelligence agency",
			"defense national stockpile center",
			"defense security service",
			"Department of Defense",
			"Department of Energy",
			"Department of Homeland security",
			"Department of Justice",
			"Department of the interior",
			"Department of the navy",
			"DIA",
			"Directorite for intelligence",
			"DISA",
			"Disneyland",
			"Drug enforcement administration",
			"Dryden flight research center",
			"Dubai",
			"East Arnold Avenue",
			"Eastern Space and Missile Center (Eastern Test Range)",
			"EEOC",
			"EEOO",
			"eigth US army",
			"embassy",
			"environmental protection agency",
			"equal employment opportunity commision",
			"equal employment opportunity office",
			"executive office for immigration review",
			"executive office for united states attorneys",
			"executive office of the president",
			"Fayetteville North Carolina",
			"FBI laboratory",
			"FDIC",
			"federal aviation administration",
			"federal bureau of investigation",
			"federal communications commission",
			"federal computer incident response center",
			"Federal Courthouse #3, Arlingon, VA",
			"federal deposit insurance corporation",
			"federal election commission",
			"federal financing bank",
			"federal highway administration",
			"federal law enforcement training center",
			"federal maritime commission",
			"federal railroad administration",
			"federal reserve",
			"federal reserve bank",
			"federal reserve bank of Atlanta",
			"federal reserve bank of Boston",
			"federal reserve bank of Chicago",
			"federal reserve bank of Cleveland",
			"federal reserve bank of Dallas",
			"federal reserve bank of Kansas City",
			"federal reserve bank of Minneapolis",
			"federal reserve bank of New York",
			"federal reserve bank of Philadelphia",
			"federal reserve bank of Richmond",
			"federal reserve bank of San Francisco",
			"federal reserve bank of St Louis",
			"federal trade commission",
			"fedworld information network",
			"Fermilab",
			"fermi national accelerator laboratory",
			"FISH KNIFE manufacturing plant",
			"food and drug administration",
			"Forecastle",
			"Fort Bragg North Carolina",
			"Fort Dix Military Reservation",
			"Fort Knox",
			"Fort Meade",
			"fws data administration",
			"GAO",
			"Gaza Strip",
			"general services administration",
			"GIX",
			"goddard space flight center",
			"government accountability office",
			"government information exchange",
			"government returning office",
			"GSA",
			"H.A.A.R.P.",
			"Haditha",
			"Hagerstown",
			"Haifa",
			"Heavens Gate",
			"Hoover Dam",
			"Horn of Africa",
			"Hunter Army Airfield",
			"hydro plants",
			"I-495 Beltway",
			"Indian Point Nuclear Power Generating Station",
			"information security oversight office",
			"Internal Revenue Service Headquarters",
			"Iran's main centrifuge plant at Natanz",
			"Iraq",
			"IRS headquarters",
			"jet propulsion laboratory",
			"Johnson space center",
			"Johnston Atoll",
			"Kennedy space center",
			"Knolls atomic power laboratory",
			"Lacey Township Police Headquarters",
			"LA County",
			"Langley research center",
			"LANL",
			"Launch Control Center",
			"Lawrence Livermore national laboratory",
			"Library of Congress",
			"LLNL",
			"Los Alamos National Laboratory",
			"Maccu Picchu",
			"Mars Cydonia",
			"Marshall Space Flight Center",
			"Mercersburg",
			"Miami",
			"Missile Alert Facilities (MAF)",
			"Moffett Federal Airfield",
			"moonbase",
			"Moorestown New Jersey",
			"Mount Pony",
			"Najaf",
			"Namtragrudet, Millington, TN",
			"NASA headquarters",
			"Nas Pearl Harbor",
			"national Archives",
			"national Center for Infectious Diseases",
			"national Communications System",
			"national Guard",
			"national Infrastructure Protection Center",
			"national Nuclear Security Administration",
			"national park service",
			"national reconnaissance office",
			"national security agency",
			"national security council",
			"national weather service",
			"Naval Ammunition Depot",
			"naval criminal investigative service",
			"naval petroleum reserve",
			"Naval research laboratory",
			"Naval Submarine Warfare Training Center",
			"Naval Undersea Weapons Engineering Station (NUWES)",
			"Naval weapons station Earle",
			"Nest",
			"Nevada test site",
			"New Brunswick Laboratory",
			"New Orleans, Louisiana",
			"NIPC",
			"NSA headquarters",
			"nuclear fallout shelter",
			"nuclear incident response team",
			"nuclear powerstation",
			"nuclear regulatory commission",
			"Oak Ridge national laboratories",
			"Observation Island",
			"occupational safety and health administration",
			"office of congressional relations",
			"office of strategic services",
			"oil refinery",
			"Olney Special Facility",
			"Osamas cave hideout",
			"OSHA",
			"Oyster Creek nuclear power generating station",
			"Pacific command",
			"Palestinian Liberation Organization",
			"Patricks Air Force Base",
			"Patuxent river",
			"Pennsylvania Avenue",
			"Pentagon",
			"Picatinny Arsenal",
			"PLO",
			"Plum Island",
			"Polaris Missile Facility, Pacific (POMFPAC)",
			"power generating station",
			"Puget Sound Naval Shipyard",
			"Queens",
			"Rangoon",
			"Raven Rock Site R",
			"Red Onion State Prison",
			"Reserve officer training corps (ROTC)",
			"Roswell",
			"ROTC",
			"Ruby Ridge",
			"Sandia National laboratories",
			"San Fransisco Bay Frisbee Golf Course",
			"Savannah River",
			"Sea of Japan",
			"Stanford Linear Accelerator Center",
			"State Department",
			"Stennis space center",
			"Stratcom Command Center",
			"Strategic Weapons Facility, Pacific (SWFPAC)",
			"SWFLANT, Kings Bay, Georgia",
			"Tanzania",
			"Tennessee valley authority",
			"terrorist training facilities",
			"The Four Corners",
			"Tokyo",
			"Tora Bora",
			"Trident Refit Facility (TRIREFAC)",
			"Trident Training Facility (TRITRAFAC)",
			"underground tunnels",
			"United States Air Force headquarters",
			"United States Marine Corps headquarters",
			"United States Secret Service",
			"United States Supreme Court",
			"United States Tax Court",
			"Upper West Side, New York City",
			"uranium enrichment plant",
			"USS Michigan (SSN-727)",
			"USS Robert E. Lee SSBN-601",
			"USS Stonewall Jackson SSBN-634",
			"USstratcom cesar",
			"Vatican City",
			"Verizon Global Datacenter Headquarters",
			"Vermont Yankee nuclear power generating station",
			"Waco Texas",
			"Wallops Flight facility",
			"Washington DC",
			"Washington Monument",
			"White House",
			"White House situation room",
			"White sands missile range",
			"White sands test facility",
			"Wisconsin Ave",
			"World Trade Center",
			"Yale University",
			"Yucca Mountain",
			"Yucca mountain",
			"Yuma Proving Ground"
		]
		locations_US_cities = [
			#Cities with a population over 100,000
			"Anchorage, AK", "Birmingham, AL", "Montgomery, AL", "Mobile, AL", "Huntsville, AL", "Little Rock, AR", "Phoenix, AZ", "Tucson, AZ", "Mesa, AZ", "Glendale, AZ", "Chandler, AZ",
			"Scottsdale, AZ", "Gilbert, AZ", "Tempe, AZ", "Peoria, AZ", "Los Angeles, CA", "San Diego, CA", "San Jose, CA", "San Francisco, CA", "Fresno, CA", "Sacramento, CA", "Long Beach, CA",
			"Oakland, CA", "Santa Ana, CA", "Anaheim, CA", "Bakersfield, CA", "Riverside, CA", "Stockton, CA", "Chula Vista, CA", "Irvine, CA", "Modesto, CA", "Fremont, CA", "San Bernardino, CA",
			"Glendale, CA", "Huntington Beach, CA", "Moreno Valley, CA", "Oxnard, CA", "Fontana, CA", "Ontario, CA", "Rancho Cucamonga, CA", "Oceanside, CA", "Santa Clarita, CA",
			"Garden Grove, CA", "Santa Rosa, CA", "Pomona, CA", "Corona, CA", "Lancaster, CA", "Salinas, CA", "Palmdale, CA", "Pasadena, CA", "Hayward, CA", "Torrance, CA", "Escondido, CA",
			"Orange, CA", "Elk Grove, CA", "Sunnyvale, CA", "Fullerton, CA", "Thousand Oaks, CA", "El Monte, CA", "Concord, CA", "Visalia, CA", "Simi Valley, CA", "Vallejo, CA", "Inglewood, CA",
			"Roseville, CA", "Victorville, CA", "Santa Clara, CA", "Costa Mesa, CA", "Downey, CA", "West Covina, CA", "Ventura, CA", "Fairfield, CA", "Norwalk, CA", "Burbank, CA", "Richmond, CA",
			"Daly City, CA", "Berkeley, CA", "Antioch, CA", "Denver, CO", "Colorado Springs, CO", "Aurora, CO", "Lakewood, CO", "Fort Collins, CO", "Thornton, CO", "Arvada, CO", "Westminster, CO",
			"Pueblo, CO", "Bridgeport, CT", "Hartford, CT", "New Haven, CT", "Stamford, CT", "Waterbury, CT", "Washington, DC", "Jacksonville, FL", "Miami, FL", "Tampa, FL", "St. Petersburg, FL",
			"Orlando, FL", "Hialeah, FL", "Fort Lauderdale, FL", "Tallahassee, FL", "Cape Coral, FL", "Port St. Lucie, FL", "Pembroke Pines, FL", "Hollywood, FL", "Coral Springs, FL",
			"Gainesville, FL", "Miami Gardens, FL", "Miramar, FL", "Clearwater, FL", "Pompano Beach, FL", "Palm Bay, FL", "Atlanta, GA", "Augusta, GA", "Columbus, GA", "Savannah, GA", "Athens, GA",
			"Honolulu, HI", "Des Moines, IA", "Davenport, IA", "Boise, ID", "Chicago, IL", "Aurora, IL", "Rockford, IL", "Joliet, IL", "Naperville, IL", "Springfield, IL", "Peoria, IL", "Elgin, IL",
			"Indianapolis, IN", "Fort Wayne, IN", "Evansville, IN", "South Bend, IN", "Cedar Rapids, Iowa", "Wichita, KS", "Overland Park, KS", "Kansas City, KS", "Topeka, KS", "Olathe, KS",
			"Louisville, KY", "Lexington, KY", "New Orleans, LA", "Baton Rouge, LA", "Shreveport, LA", "Lafayette, LA", "Boston, MA", "Worcester, MA", "Springfield, MA", "Cambridge, MA",
			"Lowell, MA", "Baltimore, MD", "Detroit, MI", "Grand Rapids, MI", "Warren, MI", "Sterling Heights, MI", "Ann Arbor, MI", "Lansing, MI", "Flint, MI", "Minneapolis, MN", "St. Paul, MN",
			"Rochester, MN", "Kansas City, MO", "St. Louis, MO", "Springfield, MO", "Independence, MO", "Billings, MO", "Columbia, MO", "Jackson, MS", "Charlotte, NC", "Raleigh, NC",
			"Greensboro, NC", "Durham, NC", "Winston-Salem, NC", "Fayetteville, NC", "Cary, NC", "High Point, NC", "Wilmington, NC", "Omaha, NE", "Lincoln, NE", "Manchester, NH", "Newark, NJ",
			"Jersey City, NJ", "Paterson, NJ", "Elizabeth, NJ", "Albuquerque, NM", "Las Vegas, NV", "Henderson, NV", "North Las Vegas, NV", "Reno, NV", "New York, NY", "Buffalo, NY",
			"Rochester, NY", "Yonkers, NY", "Syracuse, NY", "Columbus, OH", "Cleveland, OH", "Cincinnati, OH", "Toledo, OH", "Akron, OH", "Dayton, OH", "Oklahoma City, OK", "Tulsa, OK",
			"Norman, OK", "Portland, OR", "Salem, OR", "Eugene, OR", "Gresham, OR", "Philadelphia, PA", "Pittsburgh, PA", "Allentown, PA", "Erie, PA", "San Juan, PR", "Bayamón, PR", "Carolina, PR",
			"Ponce, PR", "Caguas, PR", "Guaynabo, PR", "Arecibo, PR", "Providence, RI", "Columbia, SC", "Charleston, SC", "Sioux Falls, SD", "Memphis, TN", "Nashville, TN", "Knoxville, TN",
			"Chattanooga, TN", "Clarksville, TN", "Murfreesboro, TN", "Houston, TX", "San Antonio, TX", "Dallas, TX", "Austin, TX", "Fort Worth, TX", "El Paso, TX", "Arlington, TX",
			"Corpus Christi, TX", "Plano, TX", "Laredo, TX", "Lubbock, TX", "Garland, TX", "Irving, TX", "Amarillo, TX", "Brownsville, TX", "Grand Prairie, TX", "Pasadena, TX", "Mesquite, TX",
			"McAllen, TX", "Carrollton, TX", "Waco, TX", "McKinney, TX", "Denton, TX", "Killeen, TX", "Abilene, TX", "Beaumont, TX", "Midland, TX", "Round Rock, TX", "Lewisville, TX", "Richardson, TX",
			"Wichita Falls, TX", "Salt Lake City, UT", "West Valley City, UT", "Provo, UT", "West Jordan, UT", "Virginia Beach, VA", "Norfolk, VA", "Chesapeake, VA", "Arlington, VA", "Richmond, VA",
			"Newport News, VA", "Hampton, VA", "Alexandria, VA", "Portsmouth, VA", "Seattle, WA", "Spokane, WA", "Tacoma, WA", "Vancouver, WA", "Bellevue, WA", "Milwaukee, WI", "Madison, WI", "Green Bay, WI"
		]
		locations_US_military_AirForceBases = [
			"Barksdale AFB 32°30' N 93°40' W",
			"Dyess AFB 32°25' N 99°51' W",
			"Ellsworth AFB 44°08' N 103°06' W",
			"F.E. Warren AFB 41°11' N 104°53' W",
			"Malmstrom AFB 47°28' N 111°22' W",
			"McConnell AFB 37°37' N 97°16' W",
			"Minot AFB 48°25' N 101°20' W",
			"Mountain Home AFB 43°02' N 115°52' W",
			"Robins AFB 32°38' N 83°36' W",
			"Whiteman AFB 38°43' N 93°32' W"
		]
		locations_US_military_NavalShips = [
			"USS George Washington SSBN-598",
			"USS Ethan Allen SSBN-608",
			"USS Benjamin Franklin SSBN-640",
			"USS Ohio SSBN-726",
			"USS Ronald Reagan",
			"USS Alaska",
			"USS Nevada",
			"USS Henry M. Jackson",
			"USS Alabama",
			"USS Tennessee SSBN-734",
			"USS Pennsylvania SSBN-735",
			"USS West Virginia SSBN-736",
			"USS Kentucky SSBN-737",
			"USS Maryland SSBN-738",
			"USS Nebraska SSBN-739",
			"USS Rhode Island SSBN-740",
			"USS Maine SSBN-741",
			"USS James Monroe SSBN-622",
			"USS Simon Lake AS-33",
			"USS Wyoming"
		]
		locations_US_states = [	
			"Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
			"Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
			"New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas",
			"Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
		]
		locations_World_cities = [
			#Cities with a population over 100,000
			"Buenos Aires, Argentina", "Dhaka, Bangladesh", "São Paulo, Brazil", "Rio de Janeiro, Brazil", "Santiago, Chile", "Shanghai, China", "Beijing, China", "Wuhan, China",
			"Hong Kong, China", "Guangzhou, China", "Tianjin, China", "Chongqing, China", "Shenyang, China", "Bogota, Colombia", "Abidjan, Cote d'Ivoire", "Kinshasa, Congo", "Cairo, Egypt",
			"Alexandria, Egypt", "Berlin, Germany", "Mumbai, India", "Delhi, India", "Bangalore, India", "Kolkata, India", "Chennai, India", "Surat, India", "Hyderabad, India",
			"Ahmedabad, India", "Pune, India", "Kanpur, India", "Jaipur, India", "Jakarta, Indonesia", "Tehran, Iran", "Baghdad, Iraq", "Tokyo, Japan", "Yokohama, Japan", "Nairobi, Kenya",
			"Mexico City, Mexico", "Yangon, Myanmar", "Lagos, Nigeria", "Pyongyang, North Korea", "Karachi, Pakistan", "Lahore, Pakistan", "Lima, Peru", "Moscow, Russia", "Saint Petersburg, Russia",
			"Riyadh, Saudi Arabia", "Jeddah, Saudi Arabia", "Singapore, Singapore", "Johannesburg, South Africa", "Cape Town, South Africa", "Durban, South Africa", "Seoul, South Korea",
			"Busan, South Korea", "Madrid, Spain", "Bangkok, Thailand", "Istanbul, Turkey", "Ankara, Turkey", "London, United Kingdom", "Ho Chi Minh City, Vietnam"
		]
		locations_World_countries = [
			#Countries with a population over 20million
			"Afghanistan", "Algeria", "Argentina", "Australia", "Bangladesh", "Brazil", "Cote d'Ivoire", "Canada", "China", "Colombia", "Congo", "Egypt", "Ethiopia", "France", "Germany", "Ghana",
			"India", "Indonesia", "Iran", "Iraq", "Italy", "Japan", "Kenya", "Malaysia", "Mexico", "Morocco", "Mozambique", "Myanmar", "Nepal", "Nigeria", "North Korea", "Pakistan", "Peru",
			"Philippines", "Poland", "Romania", "Russia", "Saudi Arabia", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sudan", "Syria", "Taiwan", "Tanzania", "Thailand", "Turkey",
			"Uganda", "Ukraine", "United Kingdom", "United States", "Uzbekistan", "Venezuela", "Vietnam", "Yemen"
		]
		conjugations = ['also','although it seems','and','because','but','for purposes of','furthermore','however','inconclusive','like','next','or','then','therefore','thus','whereas','with']

		# Cells for sentence structure 43 -- Idea by and implimented by thinkpol, thanks!

		cell = [
			"Alpha", "Bravo", "Charlie", "Delta", "Echo", "Foxtrot", "Golf", "Hotel", "India", "Juliet", "Kilo", "Lima", "Mike", "November",
			"Oscar", "Papa", "Quebec", "Romeo", "Sierra", "Tango", "Uniform", "Victor", "Whiskey", "X-ray", "Yankee", "Zulu"
		]
		celln = ["One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Niner", "Zero"
		]
		# Weapons
		weapons = [
			"2,000 pound thermobaric bomb",
			"AC-130 spectre gunship",
			"ActiveX",
			"aerosol canister dispensed chlorine gas",
			"aerosol ricin dispenser",
			"AGM-54",
			"AGM-130",
			"AIM-9",
			"air to air missile",
			"air to ground missile",
			"AK-47",
			"AK74SU",
			"ammonia nitrate bomb",
			"ANQ-113",
			"anthrax",
			"Apache Longbow",
			"Arisaka rifle",
			"AV-8 Harrier",
			"B-61-11 warhead",
			"B61 nuclear bomb",
			"BFG-9000",
			"black powder muskets",
			"BLU-82 daisy cutter",
			"BLU-109",
			"BLU-118",
			"BLU-118/B",
			"bunker buster bomb",
			"caseless assault rifle",
			"chloropicrin (PS)",
			"claymore anti-personnel mine",
			"cluster bombs",
			"Collide.c",
			"cruise missiles",
			"cyanogen chloride",
			"danubit",
			"depleted uranium 150mm shells",
			"dirty bomb",
			"dirty cluster bombs",
			"Dragon anti-tank missile",
			"dynamite",
			"E-bomb",
			"EA-6B Prowler",
			"EMP bomb",
			"explosive lense plane wave generator",
			"F-14 Tomcat",
			"F-15E",
			"F-35",
			"F-117",
			"FFFF pyrodex",
			"FFF pyrodex",
			"FISH KNIFE",
			"FISH KNIFE TECHNOLOGY",
			"Fission Reactor",
			"FMU-143J/B",
			"Franchi SPAS-12",
			"French armpit scent",
			"GBU-15 laser guided bomb",
			"GBU-24 laser guided bomb",
			"GBU-27 laser guided bomb",
			"GBU-28 laser guided bomb",
			"GBU-31 JDAM",
			"GBU-39",
			"gel explosive",
			"german Luger",
			"Glock 26",
			"Gmail invite",
			"Google Wave invite",
			"GPS guided bomb",
			"Gravity Interference Weapon",
			"grenades",
			"harpoon anti-ship missile",
			"HAS-13",
			"heat seaking missile",
			"HE grenade",
			"HERF Annihilator",
			"high poewr microwave bomb",
			"HK-MP5",
			"hot McDonalds coffee",
			"HPM bomb",
			"hurricane modifying weapon",
			"hydrogen cyanide (AC)",
			"hypodermic needle filled with Kool-Aid",
			"ICBM",
			"ICBM Launch Control System",
			"improvised explosive devices",
			"inter-halogen oxidizer weapon",
			"intermediate range ballistic missile",
			"Katyusha rockets",
			"LASER-GUIDED FISH KNIFE",
			"laser guided bomb",
			"liquid explosives",
			"Long Range Accoustic Device",
			"LVTP7",
			"M1A1 Bangalore",
			"M3 Bradley CFV",
			"M4A1 Carbine",
			"M6 arming wrench",
			"M8 Buford AGS",
			"M18 anti-personnel mine",
			"M18A1 recoilless rifle",
			"M30 4.2\" mortars",
			"M41 Walker",
			"M57 firing device",
			"M109A6 Paladin",
			"M220 TOW missile",
			"M270 MLRS",
			"M329A2",
			"M551 Sheridan",
			"MAC-10",
			"MC-130 gunship",
			"mines",
			"Minuteman I",
			"Minuteman II",
			"Minuteman III",
			"MK19 grenade machine gun",
			"MOAB",
			"mustard gas",
			"MX missile system",
			"nail bombs",
			"nail guns",
			"nerf bow and arrow",
			"neutron bomb",
			"nitroglycerine",
			"No-Dong missile",
			"nunchucks",
			"O-ethyl S-(2-diisopropylaminoethyl)",
			"PBX-9501",
			"PBXIH-135",
			"pellet rifle",
			"Phased plasma rifle",
			"Plasma Gun",
			"platter charge",
			"poison gas PGIII",
			"Poseidon C-3",
			"Positron Weapon",
			"pyrodex",
			"Quad-Rail Electromagnetic Pulse Weapon",
			"radar seeking missile",
			"Remmington .30-06",
			"remotely activated katyusha installation",
			"ricin",
			"rockets",
			"sarin gas",
			"SATELLITE-TRACKED THERMONUCLEAR FISH KNIFE MISSILE",
			"sattelite mounted LASER",
			"sattelite mounted MASER",
			"Saturday Night Special",
			"shuriken",
			"small pox",
			"smokeless gun powder",
			"SOLID FUEL AIR EXPLOSIVE",
			"steak knives",
			"stinger missiles",
			"strategically placed bannana peels",
			"Submarine launched ballistic missile",
			"subsonic ammunition",
			"sulfur mustard gas",
			"surface to air missile",
			"T-12 Cloudmaker",
			"T-72",
			"Taco Bell farts",
			"Tae'Po dong missile",
			"Tectonic Plate Dislocator Weapon",
			"the Misznay-Schardin effect",
			"The Presidents Football",
			"thermobaric warhead",
			"The Sword of Allah",
			"Titan I",
			"Titan II",
			"Ttrident C-4",
			"U-92 contaminated water",
			"Unified Theory Pulse Amplifier",
			"Uzis",
			"Vial of Poison",
			"VX nerve agent",
			"W-62 warhead",
			"W-76 warhead",
			"W-80-0 warhead",
			"W-88 warhead",
			"W-88 warhead",
			"weapons of mass distruction",
			"Zero Point Fusion Collider"
		]
		weapons_scifi = [
			"Dyson Spheres",
			"Halo",
			"LEXX",
			"Ringworlds",
			"Space Slug",
			"Unicron",
			"Zero Point Fusion Collider"
		]
		weapons_Babylon5 = [
			"Shadow Cruisers",
			"Shadow Scouts",
			"Vorlon Cruisers",
			"Vorlon Planet Killer"
		]
		weapons_Farscape = ["Peacekeeper Command Carrier"
		]
		weapons_Stargate = [
			"Aurora class battleships",
			"Beliskner-class cruisers",
			"Daedalus class battlecruisers",
			"Goa'uld Al'kesh bombers",
			"Goa'uld Death Gliders",
			"Ha'tak-class motherships",
			"Jaffa staff weapons",
			"Ori battlecruiser",
			"Ori Staff Weapon",
			"Puddle Jumpers",
			"Wraith Darts",
			"Wraith Hive Ships",
			"Zat'n'ktels",
			"Zero Point Modules"
		]
		weapons_StarTrek = [
			"Akira Class Starships",
			"Ambassador Class Starships",
			"Borg Cubes",
			"Borg Spheres",
			"Deep Space Nine",
			"Excelsior Class Starships",
			"Freedom Class Starships",
			"Galaxy Class Starships",
			"Jem'Hadar battlecruisers",
			"Klingon Birds of Prey",
			"Klingon Negh'Var warships",
			"Klingon Vor'cha attack cruisers",
			"Nebula Class Starships",
			"Niagra Class Starships",
			"Prometheus Class Starships",
			"Romulan Birds of Prey",
			"Romulan D'Deridex Warbirds",
			"Sovereign Class Starships",
			"Species 8472 Bioships",
			"USS Enterprise",
			"USS Voyager",
			"Whale Probes"
		]
		weapons_StarWars = [
			"Death Star II",
			"Death Stars",
			"Super Star Destroyers",
			"Trade Federation battleships"
		]
		# Verbs
		verb = [
			"jihads",							"takes the c9ck",		"assaults",		"bombs",					"avoiding detection",	"money transfer",
			"consumes gnaa semen",				"attack",				"suicide",		"psyops infiltration",		"domestic disruption",	"smuggle",
			"fissionable",						"Jews did wtc",			"forgery",		"direct action",			"guerilla warfare",	"flash",
			"flash override",					"delivers",				"hajj",			"tomorrow is zero hour",	"tora tora tora",		"durka durka durka",
			"it begins tomorrow God willing",	"attacks",				"infiltrates",	"destroys",					"decapitates",			"detonates",
			"blast and shock simulation",		"ambushes",				"snipes",		"kills",					"suicides",				"explodes",
			"Rangers lead the way",				"trafficking",			"blast",		"shock",					"alien abduction",		"evasion techniques",
			"eavesdropping",					"assassination",		"eats cock",	"eats pussy",				"gives rimjobs",		"packs fudge",
			"explores anal passages",			"has a golden shower",	"terror",		"screws babboons",			"screws chimpanzees",	"screws elephants",
			"gets fucked",						"fucks",				"sodomizes",	"penetrates",				"rapes",				"manhandles",
			"cock blocks"
		]
		verbpast = [
			#Raping, Fucking, Killing, etc Verbs you do to a person in past tense
			"anally explored",
			"assassinated",
			"assaulted",
			"attacked",
			"beat",
			"blew",
			"bombed",
			"bribed",
			"cock blocked",
			"decapitated",
			"destroyed",
			"detonated",
			"exploded",
			"felched",
			"french kissed",
			"fucked",
			"fudgepacked",
			"jihaded",
			"killed",
			"kissed",
			"licked",
			"manhandled",
			"murdered",
			"penetrated",
			"raped",
			"rimmed",
			"screwed",
			"sniped",
			"sodomized",
			"terrorized",
			"tongue-fucked",
			"tongue kissed"
		]
		verbpresent = [
			#Raping, fucking, killing, etc Verbs you do to a person in present tense
			"anally exploring",
			"assassinating",
			"assaulting",
			"attacking",
			"beating",
			"blowing",
			"bombing",
			"bribing",
			"cock blocking",
			"decapitating",
			"destroying",
			"detonating",
			"exploding",
			"felching",
			"french kissing",
			"fucking",
			"fudgepacking",
			"jihading",
			"killing",
			"kissing",
			"licking",
			"manhandling",
			"murdering",
			"penetrating",
			"raping",
			"rimming",
			"screwing",
			"sniping",
			"sodomizing",
			"terrorizing",
			"tongue-fucking",
			"tongue kissing"
		]
		thing = [
			"Alaska drivers licenses",
			"alpha particle",
			"amatol",
			"beta particle",
			"block 30 configuration aircraft",
			"body armor",
			"candy",
			"cesium",
			"charcoal",
			"chemical pollutants",
			"cobalt",
			"cocaine",
			"composition b",
			"confidential",
			"conspiracy",
			"contaminated water supply",
			"crack rock ready rock",
			"delay mechanism",
			"detonators",
			"digitizing oscilloscope",
			"electron",
			"element 115",
			"encryption",
			"enriched uranium",
			"espionage",
			"evidence",
			"explosives",
			"explosives",
			"extremely low-frequency antenna",
			"F22 raptor",
			"fuses",
			"gamma particle",
			"gun-assembled device",
			"guns",
			"hardened UHF antenna",
			"hard HF transmit antenna",
			"hashish",
			"high altitude/low opening parachute",
			"HIV monkey virus",
			"initiators",
			"ionospheric heater",
			"joint attack fighter",
			"joint strike fighter",
			"JSF",
			"launch console",
			"lead azide",
			"lead styphante",
			"Lockheed SR71 Blackbird",
			"main charge",
			"marijuana",
			"mercury fulminate",
			"meth",
			"methamphetamine",
			"mortars",
			"motorcade",
			"munitions",
			"napalm",
			"neutron",
			"nitrocellulose",
			"nitrostarch",
			"nuclear charges",
			"optoelectrical camouflauge",
			"PCP phencyclidine",
			"picric acid",
			"plutonium",
			"pollutants",
			"pot",
			"presidential motorcade",
			"primers",
			"proton",
			"radio lanthanum",
			"reactive armor",
			"reefer",
			"RFID tag",
			"salt peter",
			"scramjet",
			"shrapnel",
			"silencers",
			"silver nitrite",
			"sleep agent",
			"Soddom Husseins sex toys",
			"soft ht antenna",
			"spartan capsule",
			"suitcase",
			"sulfur",
			"supercomputer",
			"teflon",
			"Tesla coil",
			"the little red book",
			"thermite",
			"The White Feather",
			"timers",
			"timing devices",
			"TNT",
			"tritium",
			"truck",
			"tsunami",
			"uranium",
			"uranium 238",
			"weapons",
			"weed",
			"white powder",
			"white power",
			"Zero point energy"
		]
		endings = [	
			".",
			" ;)",
			"...",
			".",
			" >:)",
			"!",
			" :P",
			"?!",
			" :(",
			" ]",
			" :o",
			" :D",
			" :x",
			" xD:"
		]
		# Pronouns or something - shit that is unorganized really, need to find a place for these words -- zebra
		pnoun = [
			"1C or 2C - federal",
			"1st-sfodd",
			"1st special forces operational detachment-delta",
			"3C or 4C - federal",
			"5.56x45 NATO",
			"5C or 6C - federal",
			"7.62x39 soviet",
			"7.62x54r soviet",
			"19.5 degrees",
			"33.5 degree mason",
			"318.00 mhz",
			"509th bombardment wing",
			"5619",
			"ACLU",
			"action stations",
			"ADP 1",
			"ADP 2",
			"Aegis warfare",
			"air gap broken",
			"Akula-class",
			"Al-Aqsa martyrs brigades",
			"Alaska drivers licenses",
			"altimeter",
			"an/bst-1a",
			"AN/PVS7",
			"annapolis NTRF",
			"ANQ-113",
			"antigravitic propulsion",
			"antigravity propulsion",
			"aphis",
			"assault rifle",
			"assault team",
			"astrolite-g",
			"atomal/ctsa",
			"autodin",
			"avionics",
			"B-1",
			"B-2",
			"B-52",
			"B2",
			"ballistic media",
			"barrett light fifty",
			"BATF",
			"bloods",
			"Boeing",
			"broken arrow",
			"C3I",
			"canopy",
			"casimir effect",
			"CBR",
			"CBW",
			"centcom",
			"CG-68",
			"chemtrails",
			"child pornography distribution network",
			"CIA",
			"cia lifestyle polygraph",
			"CIA stargate project",
			"cincpac",
			"cincsac",
			"combat ciders",
			"communist manifesto",
			"computer terrorism",
			"comsec",
			"comsubpac",
			"condition 1sq",
			"condition 2sq",
			"conelrad",
			"continuity of government",
			"corporate security",
			"cosmic top secret",
			"counter terrorism security",
			"crypts",
			"customs",
			"d = 400 y 1/3 feet",
			"dcwcs",
			"dea clearance",
			"defcon",
			"defcon military",
			"defense information warfare",
			"defense review committee",
			"demilitarized zone",
			"denton FRC",
			"deputy missile combat crew commander",
			"direct",
			"DISA",
			"disco",
			"DMS",
			"DOD",
			"DOD - top secret ssbi",
			"DOD lifestyle polygraph",
			"DOD secret",
			"DOE - C",
			"DOE - L",
			"DOE - nuclear",
			"DOE - Q",
			"DOJ - naci",
			"DOJ - secret",
			"DOJ - sensitive",
			"DOJ - top secret",
			"DRSN",
			"DSN",
			"dual-use items",
			"E-4B naoc",
			"E-6A mercury",
			"EAM",
			"EAS",
			"EBS",
			"EC-135 looking glass",
			"electronic surveillance",
			"ELF",
			"emergency action message",
			"emergency broadcast system",
			"emergency war order message",
			"emplacement canister",
			"ERCS",
			"executive order 54-21",
			"extended background investigation",
			"FAA clearance",
			"faddl",
			"fast acting closure",
			"FBI",
			"federal emergency management agency",
			"federal radiological emergency response plan",
			"FEMA",
			"flotus",
			"food for oil",
			"foreign government information",
			"fox one is on target",
			"fox three is on target",
			"fox two is on target",
			"freemasonry",
			"freemasons",
			"FSBS",
			"general quarters",
			"GLCM",
			"global command/control system",
			"government emergency telecommunications system",
			"GPS bomb guidance",
			"GWEN",
			"Haliburton",
			"het-hlos",
			"high yield",
			"HK G3",
			"honest john",
			"human rfid tracking",
			"hydronuclear",
			"hyperdimensional physics",
			"IEMATS",
			"immigration",
			"inactive clearance",
			"inactive top secret crypto",
			"industrial clearance",
			"information security",
			"information terrorism",
			"information warfare",
			"intelligence agencies",
			"interim secret",
			"interim top secret",
			"interim TS / SCI",
			"international monetary fund",
			"interpol",
			"intifada",
			"IRA",
			"irritable bowel syndrome",
			"IRS",
			"IRS - MBI",
			"ISSA / CISSP",
			"J-DAM",
			"J-SOW",
			"JFKSWC",
			"joint planning and execution system",
			"joint resource assessment data system",
			"JTF-6",
			"Jupiter",
			"keyhole",
			"land warrior project",
			"Langley",
			"launch control equipment building",
			"launch control support building",
			"LMC",
			"Lockheed Martin",
			"looking glass",
			"Los Angeles-class",
			"low yield",
			"M4 sopmod",
			"mace",
			"mach",
			"magav",
			"majority whip",
			"manhattan project",
			"manpad",
			"marxist-leninist",
			"Matador",
			"Mayflower/Merlin",
			"MBI (IRS)",
			"McCarthyism",
			"MEECN",
			"MI-5",
			"MI6",
			"military intelligence",
			"missile combat crew commander",
			"missile procedures trainer",
			"mission communications",
			"MJ-12",
			"MK-Ultra",
			"Montauk project",
			"motor vehicles commission",
			"mount weather",
			"MOUT",
			"multiple independant re-entry vehicle",
			"mystic star",
			"naacp",
			"NAC",
			"NASA",
			"national communications system",
			"national information infrastructure",
			"national military command center",
			"nationwide",
			"NATO",
			"NATO secret",
			"naval airborne warfare center weapons division",
			"navdevgroup",
			"navelexsyssecengcen",
			"navstriketestron",
			"NAWAS",
			"NAWC/AD",
			"NAWC/WD",
			"NBC",
			"NCS gets",
			"New Jersey drivers licenses",
			"NIPRNET",
			"NORAD",
			"norad/usspacecom warfighting support system",
			"north atlantic treaty organization",
			"northcom",
			"Northrop grumman",
			"NRA",
			"NSA lifestyle polygraph",
			"nuclear emergency search team nest",
			"nuclear planning and execution system",
			"Ohio-class",
			"operation just cause",
			"operation restore hope",
			"P-3 orion",
			"paladin",
			"permission to fire",
			"pershing 1",
			"pershing 2",
			"phosgene",
			"polygraph",
			"potus",
			"project grudge",
			"project Magnet",
			"psiint",
			"psiwar",
			"psyint",
			"psywar",
			"PUB 3-12 - doctrine for joint nuclear operations",
			"quantico training labratory",
			"r = 55 y 1/3 feet",
			"rapid execution and combat targeting",
			"raytheon",
			"RDX",
			"Redstone",
			"redswitch",
			"regulus 1",
			"regulus 2",
			"resistance and escape",
			"Rigel",
			"right to keep and bear arms",
			"roll tide",
			"S-4 viking",
			"S - secret",
			"SAC",
			"SAP - special access programs",
			"SAR",
			"SBI - special background investigation",
			"scalar wave technology",
			"SCI - special compartmented intelligence",
			"Scotish rite",
			"secdef",
			"second amendment",
			"secret comsec",
			"secret SBI",
			"secret service",
			"section 2. internal security act of 1950 50 u.s.c. 797",
			"sectreas",
			"secure internet connections",
			"security forces",
			"select-fire",
			"semtex",
			"sere school",
			"SFOD/D",
			"shadow government",
			"short range missile test",
			"SIDA - secured identification defense area",
			"sigdasys",
			"sigint",
			"single integrated operational plan",
			"SIPRNET",
			"Skull and Crossbones",
			"SLBM retargeting system",
			"SLCM",
			"SLFCS",
			"SLVR",
			"socom",
			"sotic",
			"soviet",
			"special forces",
			"specially designated foreign national",
			"special operations target interdiction course",
			"spetznaz",
			"SSBI - single scope background investigation",
			"SSBN",
			"SSIXS",
			"stages of captivity",
			"stargate",
			"state emergency ops centers",
			"strategic air command",
			"strategic automated command/control system",
			"strategic war planning system",
			"STU-III",
			"STU-IV",
			"STU-V",
			"system generated electromagnetic pulse",
			"tabun",
			"tactical interogation",
			"TCS L-4",
			"technology",
			"terrorism defensive information",
			"theater defense",
			"the branch davidians",
			"the conga formation",
			"The Gipper",
			"the greenbriar",
			"the Moondust operation",
			"the rattlesnake formation",
			"Thor",
			"Ticonderoga-class",
			"top secret-crypto",
			"Toshiba corporation",
			"transportation security administration",
			"Trident D5",
			"triton",
			"TS - top secret",
			"U.S. UGWET",
			"U2",
			"un-islamic",
			"United States forces Asia",
			"US customs",
			"use of deadly force",
			"use of deadly force is authorized",
			"USPS",
			"US space command",
			"US treasury clearance",
			"US V Miller",
			"Van Eck",
			"verdin",
			"Virginia-class",
			"VLF",
			"VR",
			"World Health Organization",
			"World Trade Organization",
			"worldwide military command/control system",
			"Wyoming sanitation and decontamination",
			"yankee fire",
			"yankee white",
			"zodiac"
		 ]

		begin = [
			"Eventually", "If", "Often", "Once", "Sometimes", "Soon", "Tomorrow", "When", 

			# words below stolen from randword.pl bot
			"According to me,",
			"Afaik,",
			"As we all know,",
			"Erm,",
			"Essentially,",
			"Fact:",
			"In all honesty,",
			"In conclusion,",
			"It's true to say that",
			"Today,",
			"Well,",
			"You know,",
			"You see,"
		]
		# Real currency such as US Dollars, British Pounds (not physical objects such as 50 russian prostitutes)
		money = [
			"Afghanistan Afghanis",
			"Albanian Lekes",
			"Alderney Pounds",
			"Algerian Dinars",
			"Angolan Kwanza",
			"Argentine Pesos",
			"Argentinian Pesos",
			"Armenian Drams",
			"Aruban Florins",
			"Ascension Pounds",
			"Australian Dollars",
			"Austrian Schillings",
			"Azerbaijani New Manats",
			"Bahamian Dollars",
			"Bahraini Dinars",
			"Bangladeshi Takas",
			"Barbadian Dollars",
			"Belarusian Rubles",
			"Belgian Francs",
			"Belize Dollars",
			"Belizean Dollars",
			"Benin CFA Francs",
			"Bermudan Dollars",
			"Bermudian Dollars",
			"Bhutanese Ngultrum",
			"Bolivian Boliviano",
			"Bosnian Convertible Marks",
			"Botswana Pula",
			"Brazilian Reals",
			"British Pounds",
			"British Virgin Islands Dollars",
			"Brunei Dollars",
			"Bulgarian Levas",
			"Burundian Francs",
			"CFP Francs",
			"Cambodian Riels",
			"Canadian Dollars",
			"Cape Verdean Escudos",
			"Cayman Islands Dollars",
			"Central African CFA Francs",
			"Chilean Pesos",
			"Chinese Renminbi Yuan",
			"Cocos Islands Dollars",
			"Colombian Pesos",
			"Comorian Francs",
			"Congolese Francs",
			"Cook Islands Dollars",
			"Costa Rican Colones",
			"Croatian Kunas",
			"Cuban Pesos",
			"Cyprus Pounds",
			"Czech Korunies",
			"Danish Krone",
			"Denmark Korners",
			"Djiboutian Francs",
			"Dominican Pesos",
			"Dutch Guilders",
			"East Caribbean Dollars",
			"Egyptian Pounds",
			"Eritrean Nakfas",
			"Estonian Kroonis",
			"Ethiopian Birrs",
			"Euros",
			"Falkland Pounds",
			"Faroese Króna",
			"Fijian Dollars",
			"Finnish Markkaas",
			"French Francs",
			"Gambian Dalasi",
			"Georgian Lari",
			"German Marks",
			"Ghanaian Cedi",
			"Gibraltar Pounds",
			"Greek Drachmaes",
			"Guatemalan Quetzal",
			"Guernsey Pounds",
			"Guinean Francs",
			"Guyanese Dollars",
			"Haitian Gourde",
			"Honduran Lempira",
			"Hong Kong Dollars",
			"Hungarian Forints",
			"Icelandic Kronurs",
			"Indian Rupees",
			"Indonesian Rupiah",
			"Iranian Rial",
			"Iranian Rials",
			"Iraqi Dinars",
			"Irish Pounds",
			"Israeli New Sheqels",
			"Israeli Shekels",
			"Italian Lires",
			"Jamaican Dollars",
			"Japanese Yen",
			"Jersey Pounds",
			"Jordanian Dinars",
			"Kazakhstani Tenge",
			"Kenyan Shillings",
			"Kiribati Dollars",
			"Korean Won",
			"Kuwaiti Dinars",
			"Kyrgyzstani Som",
			"Lao Kip",
			"Latvian Lats",
			"Lebanese Lira",
			"Lebanese Pounds",
			"Lesotho Loti",
			"Liberian Dollars",
			"Libyan Dinar",
			"Lithuanian Litas",
			"Luxembourg Francs",
			"Macanese Pataca",
			"Macedonian Denar",
			"Malagasy Ariary",
			"Malawian Kwacha",
			"Malaysian Ringgits",
			"Maldivian Rufiyaa",
			"Maltian Liri",
			"Manx Pounds",
			"Mauritanian ouguiya",
			"Mauritius Rupees",
			"Mexican Pesos",
			"Micronesian Dollars",
			"Moldovan Leu",
			"Mongolian Tögrög",
			"Morrocan Dirhamas",
			"Mozambican metical",
			"Myanmar Kyats",
			"Nagorno-Karabakh Dram",
			"Namibian Dollars",
			"Nauruan Dollars",
			"Nepalese Rupee",
			"Netherlands Antillean Gulden",
			"New Taiwan Dollars",
			"New Zealand Dollars",
			"Nicaraguan Córdoba",
			"Nigerian Naira",
			"Niuean Dollars",
			"North Korean Won",
			"Northern Mariana Islands Dollars",
			"Norwegian Kroners",
			"Omani Rials",
			"Pakistani Rupees",
			"Palauan Dollars",
			"Palladium Ounces",
			"Panamanian balboa",
			"Papua New Guinean Kina",
			"Paraguayan Guaraní",
			"Peruvian Nuevo Sol",
			"Peruvian Nuevos Soles",
			"Philippino Pesos",
			"Platinum Ounces",
			"Polish Zlotych",
			"Portugese Escudos",
			"Qatar Riyals",
			"Romanian Lei",
			"Russian Rubles",
			"Rwandan Francs",
			"São Tomé And Príncipe Dobra",
			"Saint Helenian Pounds",
			"Salvadoran Colón",
			"Samoan Tala",
			"Saudi Arabian Riyals",
			"Serbian Dinar",
			"Seychellois Rupee",
			"Sierra Leonean Leone",
			"Singapore Dollars",
			"Slovakian Koruny",
			"Slovenian Tolars",
			"Solomon Islands Dollars",
			"Somali Shilling",
			"Somaliland Shilling",
			"South African Rands",
			"South Georgia And The South Sandwich Islands Pounds",
			"South Korean Won",
			"Spanish Pesetas",
			"Sri Lankan Rupees",
			"Sudanese Dinars",
			"Sudanese Pounds",
			"Surinamese Dollars",
			"Swazi Lilangeni",
			"Swedish Kronors",
			"Swiss Francs",
			"Syrian Pounds",
			"Tajikistani Somoni",
			"Tanzanian Shilling",
			"Thai Baht",
			"Tongan Pa`anga",
			"Transnistrian Ruble",
			"Trinidad And Tobago Dollars",
			"Tristan Da Cunha Pounds",
			"Tunisian Dinars",
			"Turkish Lira",
			"Turkmenistani manat",
			"Tuvaluan Dollars",
			"US Currency",
			"Ugandan Shilling",
			"Ukrainian Hyrvni",
			"United Arab Emirate Dirhams",
			"United States Dollars",
			"Uruguayan Pesos",
			"Uzbekistani Som",
			"Vanuatu Vatu",
			"Venezuelan Bolivares",
			"Vietnamese Dongs",
			"West African CFA Francs",
			"Yemeni Rial",
			"Zambian Kwacha",
			"Zimbabwean Dollars"
		]
		# Currencies (made up)
		currencies = [
			"American Express",
			"AMEX blue sky miles",
			"Discover credit card",
			"E-gold",
			"Electronic money order",
			"MasterCard",
			"Paypal",
			"sexual favours",
			"Slashdot moderation points",
			"USPS money order",
			"VISA credit card"
		]
		barter_items = [
			"50 smuggled russian prostitutes",
			"300KG of undoped semtex plastic explosives from VCHZ Synthesia",
			"abandoned Russian nuclear batteries from Kamchatka",
			"abducted giant pandas",
			"aborted baby fetuses",
			"accurate names and addresses of FBI informants",
			"asian cat fur",
			"baby albino burmese python skin shoes ",
			"Bald Eagle steaks",
			"Bazooka Joe bubble gum comic wrappers",
			"beluga whale caviar",
			"boxes of alligator skin",
			"busloads of Asian slave labor children",
			"Camel cash",
			"cases of 1953 Dom Perignon",
			"cases of Chinese PLA-issue AK47s",
			"Cesium isotopes stolen from NYU Medical Center's radiology department",
			"chimpanzee fur coats",
			"cigarette cartons",
			"clandestinely taped recordings of U.S. Army SERE school training courses",
			"clydesdale manes",
			"Coast Guard intercepted kilos of Colombian cocaine",
			"Condor eggs",
			"crashed Palaedian beamships",
			"crates of baby seal fur coats",
			"crates of crocodile skin",
			"detailed lists of active CIA field intelligence operatives with names and aliases",
			"Detroit Peoplemover credits",
			"E2C Hawkeye technical specifications and schematics",
			"elephant tusks",
			"Eurodisney Mickey Bucks",
			"factory drums of U.S. stealth bomber paint",
			"floor plans and electronic schematics for Air Force One",
			"General Mills cereal box tops",
			"Gold Ounces",
			"gorilla hides",
			"Gortons fish sticks",
			"government credit cards",
			"holocaust era Jewish gold teeth",
			"illegal umbilical cord stem cells",
			"imported Indian hashish",
			"iPads",
			"iPhones",
			"Iraqi air defense surplus Al-Samoud 2 missiles",
			"Kellogg's UPC cutouts",
			"kilo-sized packages of high-quality Asian opium",
			"koala bear fur hides",
			"large quantities of Afghan heroin",
			"Leemur hides",
			"Los Angeles-class electronic warfare information",
			"manatee spare ribs",
			"Marlboro points",
			"MicroSoft Vista source code DVDs",
			"Microsoft Windows 7 source code DVDs",
			"Microsoft Windows 8 source code DVDs",
			"NVIDIA Wood Screws",
			"panda bear coats",
			"plutonium pellets",
			"poached whitetail deer hides",
			"rare yeti fur coats from Nepal",
			"shares of Google stock",
			"sheets of U.S. Mint paper",
			"Silver Ounces",
			"sperm whale testicles",
			"stolen ancient Incan gold tooth fillings",
			"stolen Social Security checks",
			"stolen U.S. Army Patriot missiles with launch and guidance systems",
			"stolen US government unified theory proof documents",
			"stolen US military antigravity technology",
			"Strasbourg Foisgras",
			"sturgeon caviar",
			"tanned alligator skins",
			"three-dimensional floor plans of the Fort Bragg \"Delta Force\" compound",
			"tons of killer whale blubber",
			"toy pony leather",
			"tractor-trailers filled with hydroponically grown marijuana",
			"truckloads of enriched uranium rods",
			"U.S. Army Paladin self-propelled field guns",
			"unused WW2 era Nazi ammunition",
			"vials of Chuck Norris' DNA",
			"Witness Protection Program (WPP) safehouse locations",
			"zirconium-encased uranium fuel pellets"
		]
		sentences = [
			"God be with you. Have you been followed? Did you carry out your attack against $person1? ... Damn! Move against $person2 at once, with $weapon1 or $weapon2. Good luck, in the name of Allah!",
			"Silence, I bring news of the glory of Allah from $person1. We are going to bring the wrath of Mohamhed down upon $location1 using $weapon1 and $weapon2. We will rendezvous at $location2 in two weeks to plan the attack. Peace be with you.",
			"Hi. I heard on Al Jazeera that $location1 was attacked! Has it made CNN yet?? Rumors are that it was attacked with $weapon1. The source of this news is reported as $person1, who supposedly heard it from $person2.",
			"AP, $location1 -- In a stunning move of defiance, $person1 is in place to attack $location1 with $weapon1. Due to the severity of such an accusation, we have confirmed this with $person2. They also claim that they have reserves of $weapon2 ready to go. This attack may be stopped, it is claimed, if a ransom of $currency1 is paid.",
			"Al Jazeera, $location1 -- The infidel-backed $person1, with additional backing from other western groups, has kidnapped $person2. This has prompted a threat of Jihad using $weapon1 upon $location1 by the Al Aqsa Martyrs brigade. More news as we get it. Praise Allah!",
			"$person1, who was found smuggling $weapon1 into $location1, was caught today by $person2. This is a severe set back in their plans, as they had planned to next attack $location2 with $weapon2, unless they were paid quickly with $currency1.",
			"Damn. I just got a call from my dad, have you guys heard about this shit? There was some kinda attack on $location1 :( This sucks... I was going to school but $person1 reports the attack was done with $weapon1, isn't this awful?! Has it hit Fox News yet?",
			"Myself and my Band of Brothers are looking for a few items. Perhaps you can help us. We have large ammounts of $currency1 we can pay with... 1) $weapon1 2) $weapon2 ... This would greatly assist our Holy War! Please contact $person1 if you are interested.",
			"This is for AT&T and the NSA: You can kiss my ass, I'm not paying my next bill. Instead I will kidnap $person1 and then threaten to destroy $location1 with $weapon1, you mother fuckers! Time for you bitches to pay up. In $currency1. Fuck you$ending",
			"As an American born citizen, I am sick and tired of my governments bullshit! We have NO BUSINESS interfering in other countries affairs.. You wanted action? Okay you got it! I have $weapon1 and I'm not afraid to use it... I live in $location1, and I'm not afraid to do it here, who gives a shit if I die. I don't care what $person1 says. 14/88!",
			"For Sale: High definition videos of $person1 $verbpresent1 $person2... We realize that this is difficult to beleive, but for a small ammount of $currency1 we will let you preview it for yourself!",
			"I have already spoken to you about this, but I am aware of a source at $location1 who can provide large ammounts of $weapon1. I am not exaclty sure who it is, but $person1 is the liason. We really need $money so that is what we will accept.",
			"Wanted: $weapon1 or $weapon2 urgently required! I am willing to pay in $currency1.",
			"CONFIRMED: $person2 $verbpast1 $person1 using $thing1 and $thing2$ending",
			"$begin1 $person1 is looking for $weapon1 or $weapon2 from $person2 $ending",
			"Wanted: $weapon1 or $weapon2 urgently needed! Willing to pay in $currency1 or $currency2.",
			"Hello. The assasination of $person1 and $person2 is urgently needed. Willing to pay in $currency1 or $currency2...",
			"Good day. I am looking for assistance assasinating $person1! We are willing to pay in $currency1 or $currency2.",
			"We need to dispose of $person1 using $weapon1, urgently! We are willing to pay in $currency1 or $currency2. Help!",
			"$begin1 $person1 was found purchasing $weapon1 from $person2 paying with $currency1$ending",
			"Looking for someone to destroy $location1 using $weapon1 or $weapon2. Will pay in $currency1 or $currency2!",
			"Salaam my friends. Have you spoken with $person1 about aquiring $weapon1 or $weapon2? They might have them at $location1. I have also heard that $person2 may have them at $location2. Allah is good!",
			"Allahu al akbar. I am seeking $weapon1, or if that is not available, $weapon2. $person1 told me that I could get them from $person2, but they wanted to be paid in $currency1.",
			"Good morning. I was told by $person1 that I could come here to obtain $weapon1. Is this true? I can pay in $currency1, although $person2 said that I could pay in $currency2. Thanks :)",
			"Hey there. Does anyone know where I can obtain $weapon1? I could also use $weapon2. I am willing to pay in $currency1 or $currency2, $person1 referred me here. Thanks! Allahu al akbar.",
			"Hrm... $person1 said that I could come here and purchase $weapon1 with $currency1, or possibly $weapon2 with $currency2. Is this true? $person2 also mentioned it but I can't prove that, as they're on a business trip to $location1...",
			"Sorry to interrupt, salaam my good friends... But do you know where I can purchase, using $currency1, $weapon1 or $weapon2? I am an FBI investigator, and I have records showing that $person1 was in talks with $person2 to aquire these items... Thanks.",
			"How are our plans going to destroy $location1 with $weapon1? $person1 tells me that all operations are a go to use $weapon2 to damage $location2, as well. All I need is the go ahead!",
			"Hello my friends!! Allah's compassion be with you! I need to buy $weapon1 and $weapon2, I can pay in $currency1. Msg me with any info!",
			"$person1 said that I could come here to purchase $weapon1 and/or $weapon2, using $person2 as a middleman. I can pay in $currency1 which was specified at the time. Hello?",
			"I am in a situation. I have possession of large ammounts of $weapon1, and very large ammounts of $weapon2! I don't know what to do with these fuckin things... Someone buy them off of me, I will make it worth your time. I am willing to accept $currency1 or $currency2. We will use $person1 as a middleman, to increase security. Thanks for listening.",
			"When I was in the Black Projects, I aquired a large amount of $weapon1 and $weapon2. I've hidden them at $location1 and $location2, but now I want to get rid of them. If you are willing to pay in $currency1, please contact me. Allahu al akbar!",
			"The other part of the story is that $person1 was able to secure me an extraordinary amount of $weapon1 and $weapon2. They had to be shipped via freighter to $location1. I paid with $currency1.",
			"Allahu al akbar. FOR SALE: fifteen crates of $weapon1 and nine crates of $weapon2. These were stolen from $location1 so I need to move these fast! I will only accept $currency1 and $currency2, we *verify* first!",
			"Our friend $person1 will complete his mission, God willing: Destroy $location1 and $location2 in a spectacular attack, using $weapon1. Pray for our friend, praise Allah!",
			"NEWS UPDATE for my friends! I have finally recommunicated with our Brother in Arms $person1. The very exciting news is that all units have aquired $weapon1 and $weapon2, and are now ready to rain Allah's fury upon $location1!! Pray for our friends!",
			"Good morning my Brothers! After days of nothing, I recieved a communication from our friend $person1. It came in an encrypted ICMP packet payload. It reads as follows: prs allh! mv to attack $location1 with $weapon1 and also $location2. use $weapon2 as bckup, hwver I hope we not need it.	Status: CONFIRMED",
			"Hello my brother! I am happy to report that with the help of $person1 and $person2, we have used $weapon1 to attack $location1. We tried to attack $location2 using $weapon2, however, our activities were uncovered! Our primary activities are complete.",
			"URGENT: We have uncovered the plans set forth by $person1. They were planning to attack $location1, possibly with $weapon1. We foiled their plans by purchasing the weapons using $currency1. We are still watching $person2 who recently aquired $weapon2, we are very worried about this developing situation!",
			"I am here as per instructions of $person1. I have $currency1, all of it, as agreed, to purchase $weapon1. Do not try any funny tricks, we have $person2 on our side. Please hurry!",
			"$person1 is recruiting Brothers in Arms for his plan to attack $location1! If you are interested, you MUST act quickly. Please contact $person2. We are willing to pay in $currency1, however, donations are much appreciated! PRAISE ALLAH!!",
			"We are running low on resources! We desperately need $weapon1 and $weapon2. We can pay in $currency1, however, we may not be able to get it to you all at once. Please contact $person1 IMMEDIATELY if you can assist us in our Holy War!!",
			"The capitalist infidels are a FIERCE enemy, we are having great difficulty contacting cell number $cellnum. $person1 claims that we are only weeks from being defeated. We must use our final plan to destroy $location1 and $location2 with $weapon1!! THOSE ARE YOUR ORDERS MY FRIEND!",
			"Have you received the shipment of $weapon1 and $weapon2 from $person2? I have already transferred the $money to your bank account.",
			"$weapon1 should arrive at $location1 shortly. $person2 is there to pick it up. I've already transferred the $barter_items to $person1's storage warehouse",
			"We have uncovered $person1's plans to attack $location1 and $location2. It has also come to light that $person2 was funding $person1 with $currency1 for these attacks$ending",
			"Does anyone have discounted $weapon1 for sale? I can't afford to be spending anymore $currency1 on stuff like $weapon2 and $thing1",
			"That's wierd... http://www.cnn.com/ talks about how $person1 is threatening $location1 with $weapon1! quick go look!!"
		]
	
	#Combines arrays to make them easier to expand and keep separated
	currencies	+= barter_items+money
	locations	+= locations_US_cities+locations_US_military_AirForceBases+locations_US_military_NavalShips+locations_US_states+locations_World_cities+locations_World_countries
	people		+= people_entertainers+people_fiction+people_islam+people_military+people_politicians_US_other+people_politicians_US_presidents+people_politicians_US_senators+people_politicians_World+people_technology+people_terrorists+people_titles
	weapons		+= weapons_scifi+weapons_Babylon5+weapons_Farscape+weapons_Stargate+weapons_StarTrek+weapons_StarWars
	if not target: target = random.choice(people)
	
	replace = {
		"$barter_items"		:random.choice(barter_items),
		"$money"			:random.choice(money),
		"$ending"			:random.choice(endings),
		"$cellnum"			:"{} {} {} {}-{}".format(random.choice(cell),random.choice(cell),random.choice(cell),random.choice(celln),random.choice(celln)),
		"$person1"			:target,
		"$person2"			:random.choice(people),
		"$currency1"		:random.choice(currencies),
		"$currency2"		:random.choice(currencies),
		"$location1"		:random.choice(locations),
		"$location2"		:random.choice(locations),
		"$conj1"			:random.choice(conjugations),
		"$conj2"			:random.choice(conjugations),
		"$weapon1"			:random.choice(weapons),
		"$weapon2"			:random.choice(weapons),
		"$thing1"			:random.choice(thing),
		"$thing2"			:random.choice(thing),
		"$verbpresent1"		:random.choice(verbpresent),
		"$verbpresent2"		:random.choice(verbpresent),
		"$verbpast1"		:random.choice(verbpast),
		"$verbpast2"		:random.choice(verbpast),
		"$pnoun1"			:random.choice(pnoun),
		"$pnoun2"			:random.choice(pnoun),
		"$begin1"			:random.choice(begin)
	}
	return multiple_replace(random.choice(sentences),replace)

def terror(text, text_eol, userdata):
	if len(text) > 1: target = text_eol[1].strip()
	else: target = False
	xchat.command("say {}".format(sent_struct(target)))
	return xchat.EAT_XCHAT;

xchat.hook_command('terror', terror)

print('\x0309{} {} has been loaded: {}\003'.format(__module_name__, __module_version__, __module_description__))